GET http://localhost:8000/api/mushrooms
Content-Type: application/json

###
DELETE http://localhost:8000/api/mushrooms
Content-Type: application/json

{
  "ids": [2]
}

###
POST http://localhost:8000/api/mushrooms
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhbGljZUBleGFtcGxlLmNvbSIsImV4cCI6MTczMjc0NjE1OX0.cTfdeuMEXNnDATNBXtE3aExFSbBNW0HmAhKVDIgo8ME

{
  "mushroom_class": "e",
  "cap_diameter": 7.2,
  "cap_shape": "x",
  "cap_surface": "s",
  "cap_color": "b",
  "does_bruise_bleed": "f",
  "gill_attachment": "a",
  "gill_spacing": "c",
  "gill_color": "w",
  "stem_height": 9.5,
  "stem_width": 1.5,
  "stem_root": "e",
  "stem_surface": "i",
  "stem_color": "n",
  "veil_type": "p",
  "veil_color": "w",
  "has_ring": "t",
  "ring_type": "p",
  "spore_print_color": "o",
  "habitat": "w",
  "season": "u"
}

###
POST http://localhost:8000/mushrooms/mock-predict
Content-Type: application/json

{
  "cap_diameter": 7.2,
  "cap_shape": "x",
  "cap_surface": "s",
  "cap_color": "b",
  "does_bruise_bleed": "f",
  "gill_attachment": "a",
  "gill_spacing": "c",
  "gill_color": "w",
  "stem_height": 9.5,
  "stem_width": 1.5,
  "stem_root": "e",
  "stem_surface": "i",
  "stem_color": "n",
  "veil_type": "p",
  "veil_color": "w",
  "has_ring": "t",
  "ring_type": "p",
  "spore_print_color": "o",
  "habitat": "w",
  "season": "u"
}

### Failed
POST http://localhost:8000/mushrooms/mock-predict
Content-Type: application/json

{
  "cap_diameter": 4.3,
  "stem_height": 7.7,
  "stem_width": 9.9,
  "cap_shape": "x",
  "cap_color": "p",
  "gill_spacing": "d",
  "stem_color": "p",
  "has_ring": "f",
  "habitat": "h",
  "ring_type": "s",
  "gill_color": "b",
  "does_bruise_bleed": "f",
  "stem_root": "c",
  "veil_type": "u",
  "season": "a",
  "cap_surface": "y",
  "gill_attachment": "d",
  "stem_surface": "s",
  "veil_color": "w",
  "spore_print_color": "r"
}
